sonar.projectName=MyBus
sonar.sourceEncoding=UTF-8
sonar.sources=App.js,src
sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/.expo/**,**/dist/**,**/coverage/**,**/assets/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/styles/**,src/**/style.js
